version: '3.7'
services:
  Database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password       
      MYSQL_DATABASE: posturaltracker
      MYSQL_USER: chakib
      MYSQL_PASSWORD: ChakibHani1983
    restart: 'always'
    volumes:
      - mysql-data:/var/lib/mysql
 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'Phpmyadmin'
    links:
      - Database
    environment:
      PMA_HOST: Database
      PMA_PORT: 3306
    restart: 'always'
    ports:
      - '800:80'
volumes:
  mysql-data: