version: '3.7'

services:
  posturaltracker:
    image: posturaltracker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000" # When runing with gninx and gunicorn the port is allocated with that and not "5000:5000"
    links:
      - Database    
    restart: 'always'
    volumes:
      - .:/app
    environment:
      - DB_HOST=Database
    # networks:
    #   - gateway

  Database:
    image: hypriot/rpi-mysql # mysql:5.7 
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password       
      MYSQL_DATABASE: posturaltracker
      MYSQL_USER: chakib
      MYSQL_PASSWORD: ChakibHani1983
    restart: 'always'
    volumes:
      - mysql-data:/var/lib/mysql
    # networks:
    #   - gateway

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'Phpmyadmin'
    links:
      - Database
    environment:
      PMA_HOST: Database
      PMA_PORT: 3306
    restart: 'always'
    # networks:
    #   - gateway
    ports:
      - '800:80'
  
  nginx :
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - posturaltracker
    ports:
      - '5000:5000' 

# networks:
#     gateway: {}

volumes:
    mysql-data:

networks:
  default:
    driver: bridge
    name: posturaltracker 



 
